name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Build
      run: |
        cargo build --release
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: g8r
        path: target/release/g8r

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: g8r
        path: target/release

    - name: Remove old latest releases
      run: |
        # Set your repository name
        REPO="vangourd/g8r"
    
        # Fetch the list of releases from the GitHub API
        RELEASES=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                        https://api.github.com/repos/$REPO/releases)
    
        # Find the ID of the release tagged as 'latest'
        LATEST_RELEASE_ID=$(echo "$RELEASES" | jq '.[] | select(.tag_name == "latest") | .id')
    
        # Check if a latest release was found
        if [ -n "$LATEST_RELEASE_ID" ]; then
          # Delete the latest release
          curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               https://api.github.com/repos/$REPO/releases/$LATEST_RELEASE_ID
          echo "Deleted latest release (ID: $LATEST_RELEASE_ID)"
        else
          echo "No latest release found. Skipping deletion."
        fi
    
    - name: Create Latest Release
      id: create_latest_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: true

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_latest_release.outputs.upload_url }}
        asset_path: './target/release/g8r'
        asset_name: g8r
        asset_content_type: applicaton/octet-stream