name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - stable

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Build
      run: |
        cargo build --release
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: g8r
        path: target/release/g8r

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: g8r
        path: target/release

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref == 'refs/head/main' && 'latest' || 'stable' }}
        release_name: Release ${{ github.ref }} (${{ github.ref == 'refs/heads/main'}})
        draft: false
        prerelease: ${{ github.ref == 'refs/heads/main' }}
        body: "Description of release"
        
    - name: Upload Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./target/release/g8r
        asset_name: g8r
        asset_content_type: application/octet-stream